language: de  # Language code: 'en' for English, 'de' for German
words:
  # - gl체cklich
  - erschrecken
  - packen
  # - Gep채ck
  - schmecken
  # - St체ck
  - trocken
  - backen
  - Lacke
  - fleckig
  - dick
  - Zucker
  - eckig
  - schicken
  - schmatzen
  - putzen
  - spitzen
  - Blitz
  - Netz
  - witzig
  # - n체tzlich
  - Hitze
  - sitzen
  - spitz
  - Schatz
  - Platz
  - schwitzen
  - schmutzig
